# Generated by Django 5.0.7 on 2024-08-08 10:30

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(upload_to=articles.models.article_image_upload_handler),
        ),
    ]
